### ISSUE TITLE
Claims / Abandon All Claims

### ISSUE THREAD

**Issue by MomiLommins** [SleepingTea98/Pixelrealms#12]
In attempts to resize a claim labeled as a town, I got confused on boundaries so I attempted /AbandonAllClaims so that I could start fresh.

After using the command and attempting to set the claim it told me that the new claim was intersecting with the Town Claim that no longer existed.

**Comment by MaxIsH0t** [comment]
Maybe it's interfering with another persons claim?

**Comment by MaxIsH0t** [comment]
Show us the message it gives you when you try to create a claim on that location
