### ISSUE TITLE
Teams Commands

### ISSUE THREAD

**Issue by Tanis41493** [SleepingTea98/Pixelrealms#13]
Hello, I hope you're doing well. There's an issue with some of the Teams commands not being allowed use even by owners of said teams. All of the queue commands, (most importantly) the bank commands, none of them work.

**Comment by MaxIsH0t** [comment]
Issue Fixed!

**Comment by Tanis41493** [comment]
Perfect, thank you so much for your time and the speedy response, proving yet again that this is an awesome server to be a part of!
