### ISSUE TITLE
Time Issue

### ISSUE THREAD

**Issue by CeePee98** [SleepingTea98/Pixelrealms#3]
Time seems to be stuck, for example the time is 14:00, goes to a certain point (lets say 14:59) and then goes back to 14:00. Somehow the time seems to be moving very slowly cause it became night somehow yesterday altough this bug was happening. The restart that happened a few hours ago made it so 1 full dcycle went through, and then the time got stuck again.

**Comment by SleepingTea98** [comment]
Issue fixed
