### ISSUE TITLE
Releasing pokemon issues

### ISSUE THREAD

**Issue by Tenebrean** [SleepingTea98/Pixelrealms#9]
Able to toss a pokemon through glass blocks to initiate battle.

Tossing pokemon out in Normal Gym town makes it fall through the pixelmon grass blocks, but not minecraft blocks

**Comment by MaxIsH0t** [comment]
I've Noticed this issue yes. Looking into fixing it now!

**Comment by Tenebrean** [comment]
Pixelmon 7.0.8 says it fixed this issue on their side so im closing this, hopefully it doesn't need to be opened again
